### ISSUE TITLE
Create a tag for v0.10

### ISSUE THREAD

**Issue by graelo** [conda-incubator/conda-zsh-completion#48]
Hi,

Thanks for creating this.

Could you please create a tag for the latest version (which I believe includes `_mamba` - 8 months ago)?
That would allow package managers to create a new version including the latest changes.

Thanks!

**Comment by esc** [comment]
@graelo thank you for asking about this. The current version from `HEAD` is `0.10-dev`. If you want we can cut a release now from current `master` and that would include the recent updates. Is it that what you need?

**Comment by graelo** [comment]
Hi, thanks for the quick reply! Yes that would be awesome.

**Comment by esc** [comment]
@graelo it is done:

https://github.com/conda-incubator/conda-zsh-completion/releases/tag/v0.10

please close, if everything is satisfactory

**Comment by graelo** [comment]
Thanks, that's perfect. Closing
