### ISSUE TITLE
micromamba

### ISSUE THREAD

**Issue by bmahlbrand** [conda-incubator/conda-zsh-completion#53]
How can I get this plugin working with micromamba with antigen / oh-my-zsh in addition to conda / miniconda (conda works great!)? I see micromamba referenced here: https://github.com/conda-incubator/conda-zsh-completion/blob/2cc833a65037399bffaa149780beb2dd5376859e/_conda#L1C2-L1C32

**Comment by esc** [comment]
The top of the file reads

```
#compdef conda mamba micromamba
```

so if you can get it to work for `conda` it should also work for `mamba` and `micromamba`.

**Comment by bmahlbrand** [comment]
I figured it out, had to do with the order of the mamba hooks being initialized in zshrc. Thanks!

**Comment by esc** [comment]
@bmahlbrand awesome! Thank you for following up and closing this issue.
